[pytest]
python_files = test_*.py
pythonpath = .
testpaths = tests extractors.py filiacao.py socio.py utils.py
addopts =
    --ignore-glob=data/*
    --ignore-glob=docker/*
    --doctest-modules
    -vvvs
